global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'spring_micrometer'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['192.168.0.14:9990', '192.168.0.14:9991', '192.168.0.14:9992', '192.168.0.14:9993']

  - job_name: 'zookeeper'
    metrics_path: '/metrics'
    static_configs:
      - targets: [ '192.168.0.14:7000']